apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescale:5432
    database: eeg_monitor
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
